### PR TITLE
Adding debian buster support

### PR DESCRIPTION
**Pull request by xiamaz**
This adds support for debian 10 (codename buster).

### CODE REVIEW

**Comment by HirbodBehnam** [comment]
Thanks! Have you tested it?

**Comment by xiamaz** [comment]
I just testet it on my own buster instance, but haven't yet for debian 8 or 9.

**Comment by HirbodBehnam** [comment]
Ok I will test them on debian 9 and 8.
Thanks!
If it was good I will merge this

**Comment by HirbodBehnam** [comment]
It's ok thank you!

**Pull request merged**
